---
# SPDX-FileCopyrightText: 2023 CERN (home.cern)
#
# SPDX-License-Identifier: BSD-3-Clause

version: '1.0.0'
name: 'Simple VME FMC Carrier (SVEC)'
description: 'https://raw.githubusercontent.com/wiki/vascoguita/svec/Home.md'
website: 'https://ohwr.org/project/svec'
licenses:
  - 'CC-BY-SA-4.0'
  - 'CERN-OHL-W-2.0'
  - 'GPL-2.0-or-later'
  - 'LGPL-2.1-or-later'
images:
  - 'https://ohwr.org/project/svec/uploads/0eeb5b430351eca8a4e76a5af3892c2c/svectop_l.png'
documentation: 'https://ohwr.org/project/svec/wikis'
issues: 'https://ohwr.org/project/svec/issues'
latest_release: 'https://ohwr.org/project/svec/tags/v3.0.0'
forum: 'https://forums.ohwr.org/c/svec'
newsfeed: 'https://raw.githubusercontent.com/wiki/vascoguita/svec/News.md'
links:
  - name: 'SVEC V1 production board block diagram'
    url: 'https://ohwr.org/project/svec/uploads/e234fa371e49b0d8f0311cdd236df19c/Block.png'
  - name: 'VME64-SVEC - BO-FVM-SVEC0, Janz Tec AG, Germany'
    url: 'https://www.janztec.com/wp-content/uploads/2020/03/datasheet_vme64-svec.pdf'
  - name: 'Hardware manual (Janz Tec)'
    url: 'https://ohwr.org/project/svec/uploads/7aedb3c2fea71ef926fbbe73ab4e99ee/manual_svec_hardware.pdf'
